# Generated by Django 4.2.1 on 2023-06-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
