# Generated by Django 4.2.1 on 2023-06-21 19:09

import Portafolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to=Portafolio.models.upload_to_static)),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
