# Generated by Django 4.2.1 on 2023-06-21 18:11

import Portafolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portafolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(upload_to=Portafolio.models.upload_to_static),
        ),
    ]
