# Generated by Django 4.2.1 on 2023-06-21 18:11

from django.db import migrations, models
import inicio.models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='image',
            field=models.ImageField(upload_to=inicio.models.upload_to_static),
        ),
    ]
